image:
  file: ./Dockerfile
tasks:
  - init: pnpm install
    command: pnpm run dia:watch
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - pkief.material-icon-theme
    - mhutchie.git-graph
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - vivaxy.vscode-conventional-commits
    - sleistner.vscode-fileutils
